### ISSUE TITLE
Xcode 11.6: failed to get simulator udid, error: failed to determin latest (iOS) simulator version

### ISSUE THREAD

**Issue by KoCMoHaBTa** [bitrise-steplib/steps-xcode-test#144]
Hi, i'm getting the mentioned error. Here is the log
The stack used is Xcode 11.6
When using Xcode 11.5 - it runs fine
Please advice on what to do. Lowering the stack version is not an option.

```
+------------------------------------------------------------------------------+

| (0) xcode-test                                                               |
+------------------------------------------------------------------------------+
| id: xcode-test                                                               |
| version: 2.4.6                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-07-20T19:10:13Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[19:10:13]  * [OK] Step dependency (xcode) installed, available. 
INFO[19:10:13]  * [OK] Step dependency (go) installed, available. 
Configs:
- ProjectPath: Strowr.xcworkspace
- Scheme: Strowr
- SimulatorPlatform: iOS Simulator
- SimulatorDevice: iPhone 5s
- SimulatorOsVersion: latest
- OutputTool: xcpretty
- IsCleanBuild: false
- IsSingleBuild: true
- ShouldBuildBeforeTest: true
- ShouldRetryTestOnFail: true
- GenerateCodeCoverageFiles: false
- ExportUITestArtifacts: false
- DisableIndexWhileBuilding: true
- TestOptions: 
- XcprettyTestOptions: --color --report html --output "/Users/vagrant/deploy/xcode-test-results-Strowr.html"
- Verbose: false
- HeadlessMode: true
- CacheLevel: swift_packages
* action: -workspace
- xcodebuildVersion: Xcode 11.6 (Build version 11E708)
Checking if output tool (xcpretty) is installed
- xcprettyVersion: 0.3.0
failed to get simulator udid, error: failed to determin latest (iOS) simulator version
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | xcode-test (exit code: 1)                                     | 11.95 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-xcode-test/issues    |
| Source: https://github.com/bitrise-steplib/steps-xcode-test                  |
+---+---------------------------------------------------------------+----------+

```

**Comment by non-binary** [comment]
Hi @KoCMoHaBTa,

Can you please send a link to a build and enable support access in your project settings?

**Comment by KoCMoHaBTa** [comment]
@non-binary https://app.bitrise.io/build/e08b8b2462024acc#?tab=log

**Comment by mccallus** [comment]
Same issue: https://app.bitrise.io/build/6b870a7a75f36769#?tab=log

**Comment by omarzl** [comment]
Hello I am having this issue, half of our builds are failing today, we are using the same stack in all the builds, we have been using iPhone 8 Plus for years, suddenly today this error showed up.

I forked the repo and added logs and I found out that  `xcrun simctl list` is not showing all the devices, on the left image you can see that "== Devices ==" list is empty

Here is a failing build https://app.bitrise.io/build/513f08258a368524#?tab=log
and a non failing one https://app.bitrise.io/build/eed37a0a937149f6#?tab=log

<img width="2048" alt="Captura de Pantalla 2021-03-08 a la(s) 11 41 44" src="https://user-images.githubusercontent.com/6267487/110359714-6dc7cd00-8003-11eb-82b9-19bf64dd684d.png">

**Comment by KoCMoHaBTa** [comment]
I think i've resolved this by changing the simulator device to some newer. At the time when i reported this issue, i was using iPhone 5s, upgrading to some newer device type, eg iPhone 8 Plus, solved the issue for me.

**Comment by csk4ta** [comment]
Hi there, 👋 

Thanks so much for bringing this to our attention.

Our engineers are currently investigating this issue! I'll post it here as soon as I have any updates.

Thanks for your patience!

**Comment by csk4ta** [comment]
Hi there, 

Just wanted to let you know that the issue has been resolved. 🎉  Could you please check on your end as well? 
Thank you!

**Comment by KoCMoHaBTa** [comment]
@csk4ta I've replicated the setup form the old build and run a new one - the issue is still present.
Using Xcode 11.6 and iPhone 5s as simulator device.
https://app.bitrise.io/build/7d75e16181bc937f#?tab=log
[7d75e16181bc937f.log](https://github.com/bitrise-steplib/steps-xcode-test/files/6109102/7d75e16181bc937f.log)

**Comment by KoCMoHaBTa** [comment]
So i tried specifying iOS version and got this error - `failed to get simulator udid, error: no simulators found for os version: iOS 12.0`
Is there any additional step i'm missing in order to make the build for Xcode 11.6 and iPhone 5s on iOS 12.0 to run?

**Comment by omarzl** [comment]
You should install them first, here you have more information https://stackoverflow.com/questions/34493934/how-to-install-ios-simulators-from-command-line
